# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detector.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 500)
        MainWindow.setMinimumSize(QtCore.QSize(755, 500))
        MainWindow.setMaximumSize(QtCore.QSize(755, 500))
        MainWindow.setStyleSheet("#MainWindow{border-image: url(:/detector/detector.jpg);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 691, 361))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255,200);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 30, 601, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(34)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_video = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        font.setPointSize(14)
        self.pushButton_video.setFont(font)
        self.pushButton_video.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/other/ico/video.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_video.setIcon(icon)
        self.pushButton_video.setObjectName("pushButton_video")
        self.horizontalLayout_5.addWidget(self.pushButton_video)
        self.pushButton_model = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        font.setPointSize(14)
        self.pushButton_model.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/other/ico/model.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_model.setIcon(icon1)
        self.pushButton_model.setObjectName("pushButton_model")
        self.horizontalLayout_5.addWidget(self.pushButton_model)
        self.pushButton_start = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        font.setPointSize(14)
        self.pushButton_start.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/other/ico/start.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon2)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_5.addWidget(self.pushButton_start)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        font.setPointSize(14)
        self.pushButton_save.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/other/ico/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon3)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_5.addWidget(self.pushButton_save)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 460, 631, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_total = QtWidgets.QLabel(self.layoutWidget1)
        self.label_total.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_total.setText("")
        self.label_total.setObjectName("label_total")
        self.horizontalLayout.addWidget(self.label_total)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_good = QtWidgets.QLabel(self.layoutWidget1)
        self.label_good.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_good.setText("")
        self.label_good.setObjectName("label_good")
        self.horizontalLayout_2.addWidget(self.label_good)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_error = QtWidgets.QLabel(self.layoutWidget1)
        self.label_error.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OCR检测工具"))
        self.pushButton_video.setText(_translate("MainWindow", "选择视频"))
        self.pushButton_model.setText(_translate("MainWindow", "选择模型"))
        self.pushButton_start.setText(_translate("MainWindow", "开始计算"))
        self.pushButton_save.setText(_translate("MainWindow", "保存结果"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">报警次数：</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">应报次数：</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">误报次数：</span></p></body></html>"))
import image.image_rc
