# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        MainWindow.setMinimumSize(QtCore.QSize(800, 400))
        MainWindow.setMaximumSize(QtCore.QSize(800, 400))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#MainWindow{border-image: url(:/backgroud/backgroud.jpg);}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_view1 = QtWidgets.QLabel(self.centralwidget)
        self.label_view1.setGeometry(QtCore.QRect(61, 70, 341, 261))
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        self.label_view1.setFont(font)
        self.label_view1.setStyleSheet("background-color: rgba(255, 255, 255, 80);")
        self.label_view1.setObjectName("label_view1")
        self.label_view2 = QtWidgets.QLabel(self.centralwidget)
        self.label_view2.setGeometry(QtCore.QRect(400, 69, 331, 261))
        self.label_view2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_view2.setText("")
        self.label_view2.setObjectName("label_view2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(430, 119, 271, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_user = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.horizontalLayout.addWidget(self.label_user)
        self.lineEdit_user = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_user.setReadOnly(True)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.horizontalLayout.addWidget(self.lineEdit_user)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(430, 199, 271, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_password = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_2.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setClearButtonEnabled(True)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_2.addWidget(self.lineEdit_password)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(440, 270, 241, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(75)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_login = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/other/ico/login.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_login.setIcon(icon)
        self.pushButton_login.setIconSize(QtCore.QSize(21, 21))
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout_3.addWidget(self.pushButton_login)
        self.pushButton_quit = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("方正书宋_GBK")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/other/ico/quit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_quit.setIcon(icon1)
        self.pushButton_quit.setIconSize(QtCore.QSize(21, 21))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout_3.addWidget(self.pushButton_quit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "登录界面"))
        self.label_view1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_view1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">OCR推理评估工具</span></p></body></html>"))
        self.label_user.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">账户：</span></p></body></html>"))
        self.lineEdit_user.setText(_translate("MainWindow", "admin"))
        self.label_password.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">密码：</span></p></body></html>"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "默认密码123456"))
        self.pushButton_login.setText(_translate("MainWindow", "登录"))
        self.pushButton_login.setShortcut(_translate("MainWindow", "Return"))
        self.pushButton_quit.setText(_translate("MainWindow", "退出"))
        self.pushButton_quit.setShortcut(_translate("MainWindow", "Esc"))
import image.image_rc
